In [1]:
import numpy as np
import cv2
from sklearn.feature_extraction.image import extract_patches_2d

In [18]:
def contrast_saliency(R1, R2):
    h1, w1, n_chan = R1.shape()
    h2, w2, n_chan = R2.shape()
    N1 = h1*w1
    N2 = h2*w2
    
    return np.linalg.norm(np.mean(R1, axis=(0,1)), np.mean(R2, axis=(0,1)))
    
def extract_region(image, scale):
    pad_im = np.pad(image, scale, mode='symmetric')
    regions = extract_patches_2d(pad_im, (scale,scale))
    return regions
"""def mean_saliency(image, scale_1):
    h, w, n_chan = image.shape()
    w2 = min(h,w)
    scales_2 = [w2/2, w2/4, w2/8]
    c_mat = np.zeros((3,h,w))
    reg_1 = extract_region(image, 1)
    for s in range(3):
        reg_2 = extract_region(image, scales_2[s])
        for i range(h):
            for j in range(w):
                c_mat[s,i,j] = contrast_saliency()"""

'def mean_saliency(image, scale_1):\n    h, w, n_chan = image.shape()\n    w2 = min(h,w)\n    scales_2 = [w2/2, w2/4, w2/8]\n    c_mat = np.zeros((3,h,w))\n    reg_1 = extract_region(image, 1)\n    for s in range(3):\n        reg_2 = extract_region(image, scales_2[s])\n        for i range(h):\n            for j in range(w):\n                c_mat[s,i,j] = contrast_saliency()'

In [13]:
im = np.random.randint(0,9,(3,3))
print(im)
#im_pad = np.pad(im, 2, mode='symmetric')
reg = extract_region(im, 1)
print(reg)

[[0 2 2]
 [7 1 7]
 [3 7 0]]


NameError: name 'extract_region' is not defined